app_version: 1.8.1
capabilities: []
categories:
- security
changelog_url: https://github.com/1Password/connect/releases
date_added: '2026-02-16'
description: Securely access your 1Password items and vaults in your company's apps
  and cloud infrastructure.
home: https://developer.1password.com/docs/connect/
host_mounts: []
icon: https://media.sys.truenas.net/apps/onepassword-connect/icons/icon.svg
keywords:
- 1password
- secrets
- security
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: onepassword-connect
run_as_context:
- description: Container [api] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [sync] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/1Password/connect
title: 1Password Connect
train: community
version: 1.0.0
