app_version: 1.8.1
capabilities: []
categories:
  - security
  - tools
date_added: '2026-02-14'
description: Securely access your 1Password items and vaults in your company's apps and cloud infrastructure.
home: https://developer.1password.com/docs/connect/
host_mounts: []
icon: https://media.sys.truenas.net/apps/onepassword-connect/icons/icon.png
keywords:
  - 1password
  - secrets
  - security
lib_version: 2.2.0
lib_version_hash: ""
maintainers:
  - email: dev@ixsystems.com
    name: truenas
    url: https://www.ixsystems.com
name: onepassword-connect
run_as_context:
  - description: 1Password Connect runs as opuser (999)
    gid: 999
    group_name: opuser
    uid: 999
    user_name: opuser
screenshots: []
sources:
  - https://github.com/1Password/connect
title: 1Password Connect
train: community
version: 1.0.0
