app_version: 16.2.0
capabilities: []
categories:
- gaming
changelog_url: https://gamevau.lt/blog
date_added: '2025-02-11'
description: The self-hosted gaming platform for your DRM-free collection.
home: https://gamevau.lt
host_mounts: []
icon: https://gamevau.lt/img/logo.png
keywords:
- gaming
- self-hosted
- library
lib_version: 2.2.0
lib_version_hash: ""
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.ixsystems.com
name: gamevault
run_as_context:
- description: Container [gamevault] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/Phalcode/gamevault-backend
title: GameVault
train: community
version: 1.0.0
