app_version: 2026.2.15
capabilities: []
categories:
- ai
date_added: '2026-02-16'
description: OpenClaw is a personal AI assistant you run on your own devices. It answers
  you on the channels you already use (WhatsApp, Telegram, Slack, etc).
home: https://openclaw.ai/
host_mounts: []
changelog_url: https://github.com/openclaw/openclaw/releases
icon: https://media.sys.truenas.net/apps/openclaw/icons/icon.svg
keywords:
- ai
- assistant
- automation
lib_version: 2.2.0
lib_version_hash: 75344d294d8d9bb68ee52f390d202dc7ec8746c4ef09d1d37e599500609bedaf
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: openclaw
run_as_context:
- description: Container [openclaw] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/openclaw/openclaw
title: OpenClaw
train: community
version: 1.0.0
